# https://metallb.universe.tf/configuration/#layer-2-configuration
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: static-pool
  namespace: metallb-system
spec:
  addresses:
# MATCH ADDRESS RANGE TO LOCAL LAN NETWORK
  - 192.168.3.240-192.168.3.254
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - static-pool
