apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: test
servers: 1
agents: 2
registries:
  create: 
    name: myregistry # name of the registry container
  config: |
    mirrors:
      "cerebrum.registry":
        endpoint:
          - http://cerebrum.registry:5000
